@Library("jenlib") _

Map<String, Object> pipelineOptions = [
		projects: ["paramopt"],
		moduleOptions: [modules: ["ppu-toolchain"]],
		container: [app: "dls"],
		notificationChannel: "#jjk-notifications"
]

if (!isTriggeredByGerrit()) {
	pipelineOptions << [
			testSlurmResource: [partition: "cube", wafer: 62, "fpga-without-aout": 3],
			preTestHook: { configureHxCubeBitfile() },
			testOptions: "--test-execall -j1"
	]
}

withCcache() {
	wafDefaultPipeline(pipelineOptions)
}

// Archive plots from tests
stage(name: "Archive Test Plots") {
	runOnSlave(label: "frontend") {
		archiveArtifacts(artifacts: 'paramopt/test_results/*',
		                 allowEmptyArchive: true)
	}
}
